[project]
name = "powerhouse-bio-takehome"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ffq>=0.3.1",
    "ipykernel>=6.29.5",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]
